In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## define the vocabulary size
voc_size=10000

In [5]:
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr

[[9402, 7982, 2175, 7446],
 [9402, 7982, 2175, 1939],
 [9402, 608, 2175, 5706],
 [1129, 2867, 2403, 5288, 13],
 [1129, 2867, 2403, 5288, 426],
 [2789, 9402, 7985, 2175, 2113],
 [1968, 3992, 3052, 5288]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9402 7982 2175 7446]
 [   0    0    0    0 9402 7982 2175 1939]
 [   0    0    0    0 9402  608 2175 5706]
 [   0    0    0 1129 2867 2403 5288   13]
 [   0    0    0 1129 2867 2403 5288  426]
 [   0    0    0 2789 9402 7985 2175 2113]
 [   0    0    0    0 1968 3992 3052 5288]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 189ms/step


array([[[-0.00569732, -0.04370005, -0.00699602,  0.02251417,
         -0.0348094 ,  0.02478503,  0.00159527,  0.00492998,
         -0.0498719 ,  0.01536448],
        [-0.00569732, -0.04370005, -0.00699602,  0.02251417,
         -0.0348094 ,  0.02478503,  0.00159527,  0.00492998,
         -0.0498719 ,  0.01536448],
        [-0.00569732, -0.04370005, -0.00699602,  0.02251417,
         -0.0348094 ,  0.02478503,  0.00159527,  0.00492998,
         -0.0498719 ,  0.01536448],
        [-0.00569732, -0.04370005, -0.00699602,  0.02251417,
         -0.0348094 ,  0.02478503,  0.00159527,  0.00492998,
         -0.0498719 ,  0.01536448],
        [ 0.02259804, -0.02982844,  0.01643434,  0.03311953,
          0.00975151, -0.03461796,  0.03027445, -0.00745047,
          0.04178775, -0.04776333],
        [-0.007914  , -0.02547064, -0.02215315,  0.00784763,
          0.02543125,  0.04250217, -0.04697054,  0.00760287,
          0.04555339, -0.04846765],
        [-0.02073978,  0.00273751, -0.04947444, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9402, 7982, 2175, 7446])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 70ms/step


array([[-0.00569732, -0.04370005, -0.00699602,  0.02251417, -0.0348094 ,
         0.02478503,  0.00159527,  0.00492998, -0.0498719 ,  0.01536448],
       [-0.00569732, -0.04370005, -0.00699602,  0.02251417, -0.0348094 ,
         0.02478503,  0.00159527,  0.00492998, -0.0498719 ,  0.01536448],
       [-0.00569732, -0.04370005, -0.00699602,  0.02251417, -0.0348094 ,
         0.02478503,  0.00159527,  0.00492998, -0.0498719 ,  0.01536448],
       [-0.00569732, -0.04370005, -0.00699602,  0.02251417, -0.0348094 ,
         0.02478503,  0.00159527,  0.00492998, -0.0498719 ,  0.01536448],
       [ 0.02259804, -0.02982844,  0.01643434,  0.03311953,  0.00975151,
        -0.03461796,  0.03027445, -0.00745047,  0.04178775, -0.04776333],
       [-0.007914  , -0.02547064, -0.02215315,  0.00784763,  0.02543125,
         0.04250217, -0.04697054,  0.00760287,  0.04555339, -0.04846765],
       [-0.02073978,  0.00273751, -0.04947444, -0.01075065,  0.03162949,
         0.00061804, -0.00179201, -0.03683222